### ISSUE TITLE
Keybind info needs added to page description

### ISSUE THREAD

**Issue by Swizzler121** [realkarmakun/pvpflag#11]
I updated to the latest version in 1.20.4 when I saw you added the alternative pvp logic, (thanks again for that!) and when setting it up I was having trouble remembering what the keybind for toggling pvp on and off was, couldn't get anything to work and resorted to digging through the source code to find the keybind since you don't list it on the mod description page. 

It turned out I installed it on the server but not the client which is why it wasn't working, but still might be a good idea to note the keybind in the mod description.

**Comment by realkarmakun** [comment]
Yeah, sorry! I'll add it shortly!
