### ISSUE TITLE
PVP flag allows you to damage players with it disabled

### ISSUE THREAD

**Issue by nomanaxd** [realkarmakun/pvpflag#2]
Mod Version: 1.2.0
MC version: 1.20.1
Fabric version: .21 (i forgot the full version name)

Description: 
When a player enables the PVP mode, they are able to damage and be damaged by players that have the PVP mode disabled.

What's expected:
Players with the PVP mode disabled should not be able to be damaged or deal damage to players with the PVP mode enabled.

**Comment by Swizzler121** [comment]
I'm seeing this issue too, I'm guessing it has to do with permissions, but I haven't found any info on what permissions can be set anywhere.

**Comment by realkarmakun** [comment]
> When a player enables the PVP mode, they are able to damage and be damaged by players that have the PVP mode disabled.

Yeah! That's intended! As long no one enables PvP flag you all are safe. This is how it works in Project Zomboid.
@nomanaxd 
@Swizzler121 

Just realized description on Github is incorrect. Gonna fix it up.

**Comment by nomanaxd** [comment]
> > When a player enables the PVP mode, they are able to damage and be damaged by players that have the PVP mode disabled.
> 
> Yeah! That's intended! As long no one enables PvP flag you all are safe. This is how it works in Project Zomboid. @nomanaxd @Swizzler121
> 
> Just realized description on Github is incorrect. Gonna fix it up.

Yes the problem is when a player has PVP disabled they can be attacked still and killed by someone with it enabled.

**Comment by realkarmakun** [comment]
> Yes the problem is when a player has PVP disabled they can be attacked still and killed by someone with it enabled.


 **Enemy's skull** | **Your skull** | **Can attack happen?** 
-------------------|----------------|------------------------
 ENABLED           | ENABLED        | YES                    
 ENABLED           | DISABLED       | YES                    
 DISABLED          | ENABLED        | YES                    
 DISABLED          | DISABLED       | NO                     

Mod is essentially made so peaceful players won't accidentally damage each other. In all other cases damage can happen. So you stay on your toes when someone with a skull is coming, Or if you have it enabled you need to be aware that anyone can still damage you.

**Comment by Swizzler121** [comment]
okay, could we turn this thread into a feature request then? I downloaded this mod because I run a minecraft server for a library that normally has very-young players, they don't understand how to do console commands, so having a key to press to enable and disable pvp is a huge plus, and the graphic tied to it is even better, could you have a config option where instead of behaving how it is detailed above, you have the option to require both players to have it enabled to do PVP?

(also would be nice to have a cooldown, so someone can't attack, then immediately turn off pvp)

**Comment by realkarmakun** [comment]
> okay, could we turn this thread into a feature request then? I downloaded this mod because I run a minecraft server for a library that normally has very-young players, they don't understand how to do console commands, so having a key to press to enable and disable pvp is a huge plus, and the graphic tied to it is even better, could you have a config option where instead of behaving how it is detailed above, you have the option to require both players to have it enabled to do PVP?
> 
> (also would be nice to have a cooldown, so someone can't attack, then immediately turn off pvp)

Sorry for late reply, I'll look into alternative mode. tOnce I have some spare time in few weeks or so if I don't forget. Timer is a nice feature too. I was trying to implement it but had issues with graphics.

**Comment by Swizzler121** [comment]
Awesome, let me know if you need testers or anything, we host everything at the library locally so I can spin up a new server with whatever settings you need, I wish I could help more but I don't know java, just some basic js, php, and python.

EDIT: re-reading that it seems to imply I can spin up an externally hosted server for others, I can't as the library doesn't want to deal with that, but I can spin one up to bug test and report back. Just wanted to clarify

**Comment by alien-sunset** [comment]
likewise, I'm looking for something like toggle PVP (https://www.curseforge.com/minecraft/mc-mods/toggle-pvp) but updated to 1.20.1 

i want to allow players to choose weather they participate in pvp or not, and those who have it disabled cannot be attacked by those who have it enabled.

essentially i want that chart above to look like:

them       |   You         |   pvp
enabled   |   enabled   |   yes
enabled   |   disabled   |  no
disabled  |   enabled    |  no
disabled  |  disabled    |  no

**Comment by realkarmakun** [comment]
> likewise, I'm looking for something like toggle PVP (https://www.curseforge.com/minecraft/mc-mods/toggle-pvp) but updated to 1.20.1

Yeah sorry I don't have much time at the moment, but I hope I free up in next week or so.

**Comment by BrownTurtleBear** [comment]
any updates on this thread?

**Comment by Sugar-Pink** [comment]
Hi there, I agree with them! It should not allow someone to pvp someone else who is set to peaceful. This is how most pvp mods like this work. I'd really like to use this mod and I think I still will hence there not being many options for fabric 1.20.1 but please think about implementing an option to not allow anyone who is is peaceful (no skull) to be harmed. Thanks. :)

**Comment by realkarmakun** [comment]
Hello everyone, 

I was able to finally get some time and finish this one up. Now you can use game rule to change mod's flag logic to different one. 

Though I'm still not very happy with it since there is no easy way to setup a config without a library (at least I have not found one). All libraries look very clunky and I hate the idea of locking myself in one of them. So still looking for alternative ways to figure config out since I would like to implement some timer of sorts and cooldown system. 

Please if you have time test it out, I would greatly appreciate it!

**Comment by realkarmakun** [comment]
I also bumped fabric and MC version. Let me know if you need builds for some older versions. I can't be bothered to build them all at once, but adding them as needed would be bearable :D
