### ISSUE TITLE
Fabric API update

### ISSUE THREAD

**Issue by ItwasRonni** [realkarmakun/pvpflag#6]
Hello, are you able to make a 1.20.1 Verison that works with Fabric API 0.91.0 please?
https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/4902738

**Comment by ItwasRonni** [comment]
Or able to make the 1.20.1 version work with any version of the API :D

**Comment by realkarmakun** [comment]
Sure

**Comment by realkarmakun** [comment]
@ItwasRonni https://modrinth.com/mod/pvpflag/version/1.3.0+1.20.1
