### ISSUE TITLE
Not showing up in console or working on server. 

### ISSUE THREAD

**Issue by LegXacy** [realkarmakun/pvpflag#8]
Modpack: Prominence II [RPG]
Game version: 1.20.1
Fabric API version: 0.91.0

Hi! Unfortunately im unable to get this working no matter what I do, I have met all dependencies and still nothing works, I don't even get the gamerule you added.

**Comment by realkarmakun** [comment]
@LegXacy 
Could you please provide more info? Like server logs and client logs, preferably with attempts to use it
